version: "3.5"
services:
  mysql:
    environment:
      - MYSQL_ROOT_PASSWORD=root
    image: mysql:5.7
    ports:
      - 3306:3306
  temporal:
    depends_on:
      - mysql
    environment:
      - DB=mysql
      - DB_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PWD=root
      - MYSQL_SEEDS=mysql
      - DYNAMIC_CONFIG_FILE_PATH=config/dynamicconfig/temporal-config.yml
    image: temporalio/auto-setup:1.6.2
    ports:
      - 7233:7233
    volumes:
      - ./:/etc/temporal/config/dynamicconfig
  temporal-admin-tools:
    depends_on:
      - temporal
    environment:
      - TEMPORAL_CLI_ADDRESS=temporal:7233
    image: temporalio/admin-tools:1.6.2
    stdin_open: true
    tty: true
  temporal-web:
    depends_on:
      - temporal
    environment:
      - TEMPORAL_GRPC_ENDPOINT=temporal:7233
      - TEMPORAL_PERMIT_WRITE_API=true
    image: temporalio/web:1.6.0
    ports:
      - 8088:8088
